CREATE TABLE replenishment (
    facility_id TEXT,
    category_name TEXT,
    manufacturername TEXT,
    facility_name TEXT,
    jpin TEXT,
    title TEXT,
    pvname TEXT,
    vendor_lead_time INTEGER,
    inv_norm INTEGER,
    safety_stock INTEGER,
    vendor_id TEXT,
    vendor_name TEXT,
    current_vendor_mov REAL,
    minimum_order_criteria TEXT,
    max_allocated_space INTEGER,
    case_size INTEGER,
    cases_allocated REAL,
    space_value REAL,
    current_inventory REAL,
    max_drr REAL,
    orderedquantity REAL,
    final_suggestion REAL,
    final_cases_suggestion REAL,
    final_value REAL,
    mov_check TEXT
);